LIB_SRCS_C   = 	main.c  \
		utility.c  \
		led.c \
		system_state.c \
		json.c \
		applied_math.c \
		fifo.c \
		circular_queue.c \
		hard_ware.c \
		gprs.c \
		socket.c \
		gsm.c \
		sms.c \
		uart.c \
		nmea_protocol.c \
		gps.c \
		log_service.c \
		gps_service.c \
		agps_service.c \
		config_save.c \
		config_service.c \
		update_file.c \
		update_service.c \
		protocol.c \
		protocol_2929.c \
		command.c \
		auto_test.c\
		expmu.c\
		expmu_service.c\
		calc_wkp_time.c\
		wifi_service.c\

